---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
